version: '3.8'
services:
 api:
   build:
     context: ./api
   ports:
     - "8000:8000"
   volumes:
     - ./data:/data
     - vectorstore:/vectorstore
   env_file:
     - .env  # .envファイルを読み込む
   command: uvicorn main:app --host 0.0.0.0 --port 8000
volumes:
 vectorstore: